### ISSUE TITLE
Apparently, some TS changes make some code irrelevant?

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/is_a_ts#31]
In #5, @Krumpet said

> That sounds great. Do note that along with the reformatting, some segments are no longer relevant as they were related to a TS issue that was open at the time and has since been resolved - I haven't tested but the code could be made simpler.

I would like to learn more

**Comment by Krumpet** [comment]
My original blog post, this:

> But we get this error: Type 'T' cannot be used to index type 'typeMap'. In the case where T is not a constructor type, the compiler still doesn't narrow T down to keyof typeMap, and so tells us that we cannot safely use T as an index of typeMap. We will see this problem again later, it's an open issue that I feel is worth mentioning. I'll expand on it in an addendum.

and the entire addendum are both about an issue with generic type parameters extending union types not being narrowed. So if if had `x: X|Y` you could do `if (isX(x) { // x is X here} else { // x is Y here }`, BUT if you had `<T extends X | Y>` and `x: T` then the type of `x` wouldn't be narrowed. Since this issue has since been marked as resolved maybe the code can be cleaned up and still work.

**Comment by Krumpet** [comment]
Specifically I believe this code:

```
    const localPrimitiveOrConstructor: PrimitiveOrConstructor = className;
    if (typeof localPrimitiveOrConstructor === 'string') {
    return typeof o === localPrimitiveOrConstructor;
```

can be simplified to just use `className` directly without assigning to a local variable.

**Comment by StoneCypher** [comment]
I'm happy to fix it, or you could if you want your name more on the codebase

I will assume that what you choose here will be your general preference

**Comment by Krumpet** [comment]
Hi, I cloned the repo and tried making the changes I talked about but it looks like the bug still exists in this instance. I'll try commenting in my original SO question and on the "closed" issue.

I did make some changes in the file and the tests are still passing so I'll create a PR.

I did run into a problem running all of the test script since it uses `ls` and I'm on a windows machine at home.

**Comment by Krumpet** [comment]
[here](https://github.com/Microsoft/TypeScript/issues/13995#issuecomment-886995095) is my question on the closed issue

**Comment by StoneCypher** [comment]
> I did run into a problem running all of the test script since it uses ls and I'm on a windows machine at home.

This is surprising.  Where does it do so?  I will try to be more portable.

I'm also on a Windows machine, but I use [git bash](https://git-scm.com/downloads), so this hasn't impacted me

[Your branch builds on Windows in CI](https://github.com/StoneCypher/is_a_ts/runs/3165336635?check_suite_focus=true)

**Comment by Krumpet** [comment]
Just for reference (probably belongs in a different place, [here](https://stackoverflow.com/questions/53124124/generic-type-guard-including-primitives/53124383#53124383) is my original SO question that lead to this whole thing.

**Comment by Krumpet** [comment]
> > I did run into a problem running all of the test script since it uses ls and I'm on a windows machine at home.
> 
> This is surprising. Where does it do so? I will try to be more portable.
> 
> I'm also on a Windows machine, but I use [git bash](https://git-scm.com/downloads), so this hasn't impacted me
> 
> [Your branch builds on Windows in CI](https://github.com/StoneCypher/is_a_ts/runs/3165336635?check_suite_focus=true)

```
'ls' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! is_a_ts@0.11.5 test: `rimraf -f coverage && jest --color --coverage --verbose && ls -la coverage && ls -la coverage/spec && echo jest -c jest-stoch.config.js --color --verbose`npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the is_a_ts@0.11.5 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ran.lottem\AppData\Roaming\npm-cache\_logs\2021-07-26T19_51_58_219Z-debug.log
```

I ran `npm run test`

**Comment by StoneCypher** [comment]
oh for 

those are debugging stubs from when i was struggling to sort out a timing problem in CI

fixing 😅  sorry

**Comment by StoneCypher** [comment]
fixed in 0.14.1

https://github.com/StoneCypher/is_a_ts/commit/0ed4232b7451b9cc81eb0bc18f894e425e40bd40

**Comment by StoneCypher** [comment]
I believe @Krumpet fixed the base issue in d35d6d274f6a9b4a964b3d06f61ca6aa9d6610da

If you could confirm and close please?

**Comment by Krumpet** [comment]
The changes ended up just being some type aliases, I did not make the changes I thought I could do because it looks like the issue with "type variable extending union type is not narrowed" still persists. I believe there is a way to rewrite to simplify the code, I just haven't figured it out yet.

**Comment by Krumpet** [comment]
I think I got it!

The answer here lies in making the implementation simpler, while delegating the 'type-correctness' to overloaded function declarations, so everything is inferred correctly while the implementation stays simple. Hopefully I can get a PR online tonight ( = in a few hours).

```typescript
function typeGuard<T extends Constructor>(o: unknown, className: T): o is ConstructedType<T>;
function typeGuard<T extends keyof typeMap>(o: unknown, className: T): o is typeMap[T];


// finally, guard ALL the types!
function typeGuard(o: unknown, className: PrimitiveOrConstructor) {

  if (isPrimitiveName(className)) {
    return typeof o === className;
  }

  return o instanceof className;
}


function isPrimitiveName(className: PrimitiveOrConstructor): className is keyof typeMap {
    return (typeof className === 'string')
}
```

**Comment by StoneCypher** [comment]
Merjt.

Following f09e77accea5ce4b6324f3d4c7ab4a215df87c5a, does this now feel open or closed to you?

**Comment by Krumpet** [comment]
Closed, yeah.

**Comment by StoneCypher** [comment]
Fixed in f09e77a
